name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       java-version: [ 8, 11, 15, 16, 17 ]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: ${{ matrix.java-version }}
  #   - name: Compile with Maven
  #     run: mvn -T 1C clean generate-sources compile --file pom.xml
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"   
          
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       java-version: [ 8, 11, 15, 16, 17 ]   
  #   needs: [build]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: ${{ matrix.java-version }}
  #   - name: Test with Maven
  #     run: mvn -T 1C test-compile test --file pom.xml
  
  sonarcloud:
    environment: sonarcloud
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: SonarCloud Scan
      run: mvn clean test jacoco:report org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=Dyy22_emv-qrcode -Dsonar.organization=dyy22 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  # deploy-package:
  #   runs-on: ubuntu-latest
  #   needs: [build, test, sonarcloud]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 17
  #   - name: Deploy Package
  #     run: mvn deploy
  #     env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-package:
    runs-on: ubuntu-latest
    needs: [build, sonarcloud]
    steps:
    - uses: actions/checkout@v1
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      with:
        git-release-bot-name: "bot-idhub"
        git-release-bot-email: "bot@idhub.io"
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
